name: Build and Push Docker Image for recipe-book-appv12-qa
on:
  push:
    branches:
      - "main"
    paths:
      - 'recipe-book-appv12-qa/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: assistoshectoride
      IMAGE_NAME: recipe-book-appv12-qa
      PROJECT_SUBDIRECTORY: recipe-book-appv12-qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.PROJECT_SUBDIRECTORY }}
          file: ./${{ env.PROJECT_SUBDIRECTORY }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
